-- Lets a Pack Order be saved as a persistent record (recipient, address, package info, and a
-- snapshot of the line items) instead of only existing for the current session. Order numbers
-- follow the same shape as BTK numbers — a 3-letter prefix + 6 zero-padded digits — generated by
-- a dedicated sequence so numbering is unique and gapless-in-practice without any client-side
-- coordination.
--
-- Line items are stored as a jsonb snapshot ([{btk, qty, packed, backorder}]) rather than a
-- separate order_items table — simplest option for "what did this order contain", and this app
-- has no reporting/joins need beyond that today. Revisit if that changes.
--
-- Run once in the Supabase SQL Editor, after the earlier migrations.

create sequence if not exists public.orders_number_seq;

create table public.orders (
  id bigint generated always as identity primary key,
  order_number text not null unique default ('ORD' || lpad(nextval('public.orders_number_seq')::text, 6, '0')),
  warehouse_id text not null references public.warehouses(l),
  recipient_name text,
  recipient_address text,
  box_length numeric,
  box_width numeric,
  box_height numeric,
  box_weight numeric,
  items jsonb not null,
  created_at timestamptz default now(),
  created_by uuid references auth.users(id)
);

alter table public.orders enable row level security;

-- Same viewer/editor/admin shape as items: read scoped to your own warehouse (or admin sees all),
-- create/update for editor+admin, delete admin-only.
create policy p_orders_select on public.orders for select to authenticated using (
  warehouse_id = (select warehouse_id from public.profiles where id = auth.uid())
  or (select role from public.profiles where id = auth.uid()) = 'admin'
);
create policy p_orders_insert on public.orders for insert to authenticated with check (
  (select role from public.profiles where id = auth.uid()) in ('editor', 'admin')
  and (
    warehouse_id = (select warehouse_id from public.profiles where id = auth.uid())
    or (select role from public.profiles where id = auth.uid()) = 'admin'
  )
);
create policy p_orders_update on public.orders for update to authenticated using (
  (select role from public.profiles where id = auth.uid()) in ('editor', 'admin')
);
create policy p_orders_delete on public.orders for delete to authenticated using (
  (select role from public.profiles where id = auth.uid()) = 'admin'
);

grant select, insert, update, delete on public.orders to authenticated;
grant usage on sequence public.orders_number_seq to authenticated;
